### ISSUE TITLE
[IMPROVEMENT] - ImageUtilities Fullscreen, close on click.

### ISSUE THREAD

**Issue by shelbyKiraM** [mwittrien/BetterDiscordAddons#1294]
**Describe the solution you'd like**
I'd like to open a layer with a partly transparent bg over my current desktop fullscreen and simply close the preview when I click anywhere in the overlay aside from a button.
```js
document.querySelector('.layer-2KE1M9').requestFullscreen();
```
launches the image preview fullscreen but uses macOS's native fullscreen, in a new desktop, not as an overlay (I'm thinking like Telegram).

**Describe alternatives you've considered**
I've tried simply running it from inspector but it's not exactly what I want. You may have some deeper ideas about it.

Here's my Custom CSS about the image preview:
```css
/* imageWrapper tweaks */
.modal-qgFCbT .imageWrapper-2p5ogY {
	overflow: visible !important;
	width: 98vw !important;
	max-height: 100vh;
	height: 0 !important;
	position: relative;
}
.modal-qgFCbT .imageWrapper-2p5ogY img, .modal-qgFCbT .imageWrapper-2p5ogY video {
	position: fixed;
	top: calc(47vh - 35px);
	left: 50vw;
	transform: translateY(-50%) translateX(-50%);
	max-width: 96vw;
	width: auto !important;
	height: auto !important;
	max-height: calc(94vh - 70px) !important;
	object-fit: scale-down;
	border-radius: 10px;
}
.operations-3V47CY {
	position: fixed;
	bottom: 0;
	right: 0;
	padding: 2px 9px;
	z-index: 99;
}
.operations-3V47CY a {
	padding: 5px !important;
	line-height: 17px;
	top: 0px;
}
a.downloadLink-1ywL9o {
	display: block !important;
	opacity: 1;
	background: rgba(255,255,255,0.2);
	border: 1px solid rgba(248,248,242,0.85);
	border-radius: 10px;
	color: #f2f2f8 !important;
	padding: 2px 9px;
}
.downloadLink-1ywL9o: nth-child(5) {
	background: #50fa7b;
	color: #282a36 !important;
}
.operations-3V47CY .downloadLink-1ywL9o: nth-child(n+6) {
	display: none !important;
}
.details-9dkFPc {
	color: #f2f2f8;
	margin-top: 0 !important;
	font-size: 12px !important;
	line-height: 10px;
}
/* Dracula for image details */
.detailsWrapper-TE1mu5 {
	text-shadow: 1px 1px 4px #282a36;
	text-shadow: 1px 1px 4px #282a36;
	color: #f2f2f8;
}
.backdrop-1wrmKB {
	/* opacity: 0.5 !important; */
	background: #282a36 !important;
}
.sibling-6vI7Pu img {
	visibility: hidden;
}
/* My fancy things above messed up the .toast */
.toasts-tApoHv {
	top: 50%;
	right: auto;
	left: 50%;
	transform: translate(-50%);
}
```
