### ISSUE TITLE
[BUG] - DiscordRecolor

### ISSUE THREAD

**Issue by shamshitty** [mwittrien/BetterDiscordAddons#2260]
**Describe the bug**
File icons are misaligned

**To Reproduce**
Install DiscordRecolor, enable it, send a file that doesnt "embed" like a video or text file

**Expected behavior**
File icons to be aligned correctly

**Screenshots**
with theme
![image](https://user-images.githubusercontent.com/68004605/226219010-0cc3b677-830c-43ce-9d9e-90dc90d85b39.png)

without theme
![image](https://user-images.githubusercontent.com/68004605/226219023-96cd7c9b-1032-457d-b218-e96946a5907a.png)

**Discord Build (stable, ptb or canary):**
Stable

**Additional context**
Fixing this with css in turn misaligns this icon
![image](https://user-images.githubusercontent.com/68004605/226219178-9a1db009-b237-43c4-acee-01f74d078e96.png)

```css
/** selectors used match those appearing in dev tools **/

/* zip file */
.attachment-1PZZB2 .icon-1KCy88 + *::before,
.attachment-1PZZB2 .icon-1KCy88 + *::after {
  top: 16px;
  left: 16px;
}
```
