### ISSUE TITLE
[BUG] - EmojiReplace no longer works in emoji picker after Discord icons update

### ISSUE THREAD

**Issue by D3SOX** [mwittrien/BetterDiscordAddons#2580]
**Describe the bug**
Discord updated their icons which apparently also changed something that makes EmojiReplace no longer function inside the emoji picker right now

**To Reproduce**
Use latest Discord stable

**Expected behavior**
Work

**Screenshots**
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/24937357/ad3a9e8e-e8ac-4322-ab48-27044c597810)

**Discord Build (stable, ptb or canary):**
Stable 251616 (de34f8e)

**Additional context**
Seems like they end with `.png` instead of `.svg` now
![image](https://github.com/mwittrien/BetterDiscordAddons/assets/24937357/7f4dac0a-3be8-4cd2-9c1a-e56cab51aa2b)
and are loaded from a sprite

Changing all `url("/assets/ca08a028c938ce8c89a3.png")` to `url("https://github.com/mwittrien/BetterDiscordAddons/blob/master/Themes/EmojiReplace/spritesheets/JoyPixels/emoji_64.png?raw=true")` makes it work again

For example this fixes it for people emoji
```css
.emojiSpriteImage__6363e[style*='background-image: url("/assets/ca08a028c938ce8c89a3.png")'] {
  background-image: url("https://github.com/mwittrien/BetterDiscordAddons/blob/master/Themes/EmojiReplace/spritesheets/JoyPixels/emoji_64.png?raw=true") !important;
}
```
but it's not yet correctly aligned

![image](https://github.com/mwittrien/BetterDiscordAddons/assets/24937357/c831838a-1201-4f73-bd4f-71ec5021d686)

I would have created a PR, but I think you still use tools which the source code is not available for.
