### ISSUE TITLE
[BUG] - DiscordRecolors breaks bd-settings slider style

### ISSUE THREAD

**Issue by nicola02nb** [mwittrien/BetterDiscordAddons#2851]
**Describe the bug**
DiscordRecolors breaks bd-settings slider style by making it thicker

**To Reproduce**
Open some settings of a plugin that has a slider generated with BdApi

**Expected behavior**
Shoul be mor thin...

**Screenshots**
How it is
![image](https://github.com/user-attachments/assets/6f38781f-c26b-4633-997e-faa01fdd9224)
How it should be
![image](https://github.com/user-attachments/assets/af50ff8b-f97e-4995-9443-82b366e61e21)

**Discord Build (stable, ptb or canary):**
Which build of Discord are you using.

**Additional context**
Replacing 
``` CSS
.bd-slider-input {
    background-color: var(--background-accent);
}
```
With 
``` CSS
.bd-slider-track {
    background-image: linear-gradient(var(--background-accent), var(--background-accent));
}
```
Should work
