### ISSUE TITLE
[IMPROVEMENT] - EditUsers: The ability to set Custom Emoji as Bottag Icon.

### ISSUE THREAD

**Issue by Riddim-GLiTCH** [mwittrien/BetterDiscordAddons#2891]
**The Ability to set Custom Emoji As Bottag Icon.**
EditUsers allows you to set a customized bottag for specific users. I've used this feature for a while now to make my closer friends stand out more. Some of these friends have a certain icon of for example a certain character they are very excited about. And they have emojis of these characters that they often use.

I'd like to be able to put these emojis in their bottags to make these tags more unique to them.

**Describe alternatives you've considered**
I currently have a working implementation working in PureCSS. but adding a new user to this is a bit cumbersome, and I dont think everyone is as well versed in CSS is. And im not even that good... 😵‍💫

**Additional context**
Proof of Concept in pure CSS:
![](https://RDG.monarchuploader.de/content/cdn/XSttpGbhXIjS/Discord_v6hfUyD5Bh.png)
![](https://RDG.monarchuploader.de/content/cdn/lhuOMULxpgRr/Discord_8D8v10m5Nw.png)
![](https://RDG.monarchuploader.de/content/cdn/QDFeWjEuBBug/Discord_33U7JV7R2N.png)

CSS used to achieve this for reference
```CSS
/* Custom User Tag BS */
.header_c19a55:has( [src*="473880177609277451"]/*Kapten*/),
.inner_c0bea0:has( [src*="473880177609277451"]/*Kapten*/) {
  .botTag_c19a55 .botText__82f07::before,
  .botText__82f07::before {
    content: url('https://cdn.discordapp.com/emojis/306195485213982720.png?size=16');
    padding-right: 5px;
  }
}
```
