### ISSUE TITLE
[IMPROVEMENT] - BetterFriendsList - Expose User Profile Elemetns in Friends list

### ISSUE THREAD

**Issue by Riddim-GLiTCH** [mwittrien/BetterDiscordAddons#2991]
**Expose Elements of the User Profile in the friends list:**
Expose things like the banner image and the profile colors on A user's entry in the friendslist. This can be exposed for theming purposes, for example: Allowinng for the profile colors or banner to be used as background for each individual entry.

**An example:**
I took the librety of writing an example CSS snippet of how this could be utilized. The variable names are placeholders. They could be anything that would make sense.

```css
.peopleListItem_cc6179 {
    position: relative;
    background: linear-gradient(to bottom, var(--profileaccent), var(--profileprimary));
    overflow: hidden;
    display: flex;
    align-items: center;
    padding: 15px;
    border-radius: 8px;
}
.peopleListItem_cc6179::after {
    content: "";
    position: absolute;
    top: 0;
    right: 0;
    width: 25%;
    height: 100%;
    background: url('https://i.imgur.com/GztzwIY.png');
    background-size: cover;
    background-position: top;
    background-repeat: no-repeat;
    z-index: 1;
    opacity: 0.5;
}
.peopleListItem_cc6179:nth-child(3) .listItemContents_fc004c {
    width: 75%;
    z-index: 2;
    opacity: 0.75;
}
```

Visual Mockup of what the above code would look like (with placeholder assets:
![Image](https://github.com/user-attachments/assets/66597376-3355-49e1-b78c-001ed4d571ac)

**Additional context**
